name: Deploy davidgasquez.com

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Trigger website deploy workflow
        env:
          GH_TOKEN: ${{ secrets.SITE_DEPLOY_TOKEN }}
        run: gh workflow run deploy.yml --repo davidgasquez/davidgasquez.com --ref main
